language: java
matrix:
  include:
  - os: linux
    jdk: oraclejdk8
#  - os: osx
#    osx_image: xcode8
script:
- cd azure-documentdb-rx
- mvn dependency:resolve
- zip -d $HOME/.m2/repository/com/microsoft/azure/azure-documentdb/1.11.0/azure-documentdb-1.11.0.jar 'META-INF/*.SF' 'META-INF/*.RSA' || echo "maybe already fixed and cached!" 
- mvn test -P fast -DargLine="-DACCOUNT_HOST=$ACCOUNT_HOST -DACCOUNT_KEY=$ACCOUNT_KEY" cobertura:cobertura
after_success:
  - bash <(curl -s https://codecov.io/bash)


cache:
  directories:
  - $HOME/.m2
