language: java

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: linux
      dist: trusty
      jdk: openjdk8 
    - os: osx
      jdk: oraclejdk8

script: cd azure-documentdb-rx && mvn clean package

# uncomment and edit the following line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
