language: java
matrix:
  include:
  - os: linux
    jdk: oraclejdk8
  - os: osx
    osx_image: xcode8
script:
- cd azure-documentdb-rx
- mvn dependency:resolve
- zip -d ~/.m2/repository/com/microsoft/azure/azure-documentdb/1.11.0/azure-documentdb-1.11.0.jar 'META-INF/*.SF' 'META-INF/*.RSA'
- mvn test -P fast -DargLine="-DACCOUNT_HOST=$ACCOUNT_HOST -DACCOUNT_KEY=$ACCOUNT_KEY"
