language: java
sudo: false
jdk:
- oraclejdk8
script:
- bash ./tools/sync_runtimes.sh
- mvn install -DskipTests=true
- mvn -pl !azure-batch,!azure-mgmt-website checkstyle:check
- mvn package javadoc:aggregate -DskipTests=true
env:
  global:
    secure: bB/RoMrP+sMJBZB6G/s4tPhZUyY0DEEszKd1Vne4TTebHnfzeHQDABYWfcJNVeWujlGJmyi78bvyysm6lfhAnDtIQXss+P+ryN53QDZmU8zKmzZIiqRS8IAMEKRhy03/J62RBQX+F52iP3hUykSHlAxV0lmdWIVtVtp0au8Lu+XmptjXDtVzT87anr879Olyc8Ax2izR0EYZpten6CEYKktx6lUoSIWBTYvrUs1ouboK3X1PpKqdVvvt16rswK36zCt7j0b3DTl8F5kinP67dP42f+Kix2IWGtFjcQbXd7Wdd/d8Ouy9BTlsG5wQNk4ChjITYxGZf3p9DupPKlEe7sA+N9ZS2w4iTcNucI/mkRtDVawDqxmPwfbmqkt9KXHBODS1sTmsrSys870sW3bKwAauaUMpJJAkWYXuNXm8iUVGa5nE3u+YB410puRmbXa5c3QbzVrftohIKM/3RvpUDXjXVAJuiLktC0sHvQ3iRS/N07AjjTGdst1oB1zpf8hlgzJzJ8PrGad5/DHGH1WoWQSbJffDCrKf92U1eLVs02Y3RGKSJ+iiXTWsnOGsgy6RVZcKv7AJp3R+uCwVE0dLoSVjhJaIt4zXcUuwN4uUlAOVsIoaWZ6c5UINWHzjuy6IWM+mId4kFYqn8shoDvsgYAZsJctqbqdUtpQVoWCjmiw=
